FROM php:7.2-apache

# COPY unidad_6 /var/www/html/

# Instalando node
RUN curl --silent --location https://deb.nodesource.com/setup_12.x | bash - \
    && apt-get install --yes nodejs \
    && apt-get install --yes build-essential

RUN npm install -g firebase-tools

USER root